server:
  port: 8761

eureka:
  instance:
    #    hostname: localhost
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/

#  server:
#    enable-self-preservation: false